disabled_rules:
- missing_docs


- operator_usage_whitespace
- operator_whitespace
- overridden_super_call
- private_outlet
- private_unit_test
- prohibited_super_call
- redundant_nil_coalescing
- redundant_string_enum_value
- return_arrow_whitespace
- statement_position
- switch_case_on_newline
- syntactic_sugar
- todo
- trailing_comma
- trailing_newline
- trailing_semicolon
- trailing_whitespace
- type_body_length
- type_name
- unused_closure_parameter
- unused_enumerated
- valid_docs
- valid_ibinspectable
- variable_name
- vertical_whitespace
- void_return
- weak_delegate

opt_in_rules:
- attributes
- closing_brace
- closure_end_indentation
- closure_parameter_position
- closure_spacing
- colon
- comma
- conditional_returns_on_newline
- control_statement
- cyclomatic_complexity
- custom_rules
- dynamic_inline
- empty_count
- empty_parameters
- empty_parentheses_with_trailing_closure
- explicit_init
- file_header
- file_length
- first_where
- force_cast
- force_try
- force_unwrapping
- function_body_length
- function_parameter_count
- implicit_getter
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- legacy_nsgeometry_functions
- line_length
- mark
- nesting
- nimble_operator
- number_separator
- opening_brace

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage

line_length:
  warning: 200
  error: 250
